### ISSUE TITLE
Linux install fails on final `yarn` command (Fedora)

### ISSUE THREAD

**Issue by tandy-1000** [satchelspencer/repsyps#16]
```gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/tandy/Programming/repsyps/build'
  CXX(target) Release/obj.target/audio/src/native/addon.o
make: g++: No such file or directory
make: *** [audio.target.mk:135: Release/obj.target/audio/src/native/addon.o] Error 127
make: Leaving directory '/home/tandy/Programming/repsyps/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tandy/Programming/repsyps/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.9.11-200.fc33.x86_64
gyp ERR! command "/usr/bin/node" "/home/tandy/Programming/repsyps/node_modules/.bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/tandy/Programming/repsyps
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.```

I followed the guide to try and install on fedora but got this error.

**Comment by dieseltravis** [comment]
I'm on Pop!_OS and get a different error related to some missing DspFilters:
```
❯ yarn
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
$ node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.22.9 | linux | x64
gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/travis/Projects/github/repsyps/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/Projects/github/repsyps/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/Projects/github/repsyps/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/.cache/node-gyp/12.22.9/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/travis/.cache/node-gyp/12.22.9',
gyp info spawn args   '-Dnode_gyp_dir=/home/travis/Projects/github/repsyps/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/travis/.cache/node-gyp/12.22.9/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/travis/Projects/github/repsyps',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/travis/Projects/github/repsyps/build'
  CXX(target) Release/obj.target/audio/src/native/addon.o
In file included from ../src/native/audio.h:8,
                 from ../src/native/addon.cc:2:
../src/native/state.h:9:10: fatal error: DspFilters/Dsp.h: No such file or directory
    9 | #include <DspFilters/Dsp.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [audio.target.mk:137: Release/obj.target/audio/src/native/addon.o] Error 1
make: Leaving directory '/home/travis/Projects/github/repsyps/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/Projects/github/repsyps/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 6.0.12-76060006-generic
gyp ERR! command "/usr/bin/node" "/home/travis/Projects/github/repsyps/node_modules/.bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/travis/Projects/github/repsyps
gyp ERR! node -v v12.22.9
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I think mine is missing https://github.com/vinniefalco/DSPFilters/tree/master/shared/DSPFilters/include/DspFilters but I'm not sure where they'd go.

**Comment by dieseltravis** [comment]
Well I copied the DspFilters folder and all the files in this folder https://github.com/FFTW/fftw3/tree/master/api into the src/native folder and it compiled successfully.
